#!/bin/sh
### BEGIN INIT INFO
# Provides:          lvgldemo
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

DAEMON=/usr/bin/lvgldemo_32FS
NAME=lvgldemo

case "$1" in
    start)
        echo "Starting $NAME"
        export HOME=/root
        start-stop-daemon -S -b -m -p /var/run/$NAME.pid -x $DAEMON
        ;;
    stop)
        echo "Stopping $NAME"
        start-stop-daemon -K -p /var/run/$NAME.pid || true
        rm -f /var/run/$NAME.pid
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
